#
# Makefile for ccic devices
#

obj-$(CONFIG_CCIC_NOTIFIER)	+= ccic_notifier.o ccic_sysfs.o ccic_core.o ccic_misc.o
obj-$(CONFIG_CCIC_S2MM005)		+= s2mm005_fw.o s2mm005_cc.o s2mm005_pd.o s2mm005.o ccic_alternate.o